[project]
name = "gaitmod"
version = "0.1.0"
description = "Real-time gait modulation prediction using multimodal neural and movement data (LFP, EEG, IMU, EMG) — designed for closed-loop DBS systems in Parkinson's diseas."
authors = [{name = "Mohammad Orabe", email = "orabe.mhd@gmail.com"}]
readme = "README.md"
requires-python = ">=3.8" 
license = {file = "LICENSE"}

dependencies = [
    "antropy",
    "imbalanced-learn",
    "matplotlib",
    "mne",
    "numpy", # Version will be constrained by TensorFlow via environment.yml
    "pandas",
    "pyyaml",
    "scikit-learn",
    "scipy",
    "seaborn",
    "tqdm",
    "pydot",
    "tensorflow" # Generic TensorFlow dependency
]

[project.optional-dependencies]
viz = ["pydot"]
# dev = ["pytest", "black", "flake8"]

keywords = [
    "machine-learning", 
    "deep-learning", 
    "gait", 
    "modulation", 
    "brain-computer-interface", 
    "signal-processing", 
    "deep-brain-stimulation", 
    "closed-loop-dbs",
    "parkinsons", 
    "BCI", 
    "ML", 
    "LFP", 
    "EEG", 
    "IMU", 
    "EMG", 
    "dbs"
]

# classifiers = [
#     "Development Status :: 3 - Alpha",
#     "Intended Audience :: Developers",
#     "Intended Audience :: Science/Research",
#     "License :: OSI Approved :: MIT License",
#     "Programming Language :: Python :: 3",
#     "Programming Language :: Python :: 3.8",
#     "Programming Language :: Python :: 3.9",
#     "Programming Language :: Python :: 3.10",
#     "Topic :: Scientific/Engineering :: Artificial Intelligence",
#     "Topic :: Scientific/Engineering :: Medical Science Apps."
# ]

[project.urls]
Homepage = "https://github.com/orabe/gaitmod" # 
Documentation = "https://gaitmod.readthedocs.io/"
Repository = "https://github.com/orabe/gaitmod"
"Bug Tracker" = "https://github.com/orabe/gaitmod/issues"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

